[[redirects]]
  from = "/booking"
  to = "/booking/"
  status = 301

[[redirects]]
  from = "/booking/reserve"
  to = "/booking/reserve/"
  status = 301

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
